name: immatch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - pytorch==1.7.0
  - torchvision
  - jupyter
  - scipy
  - matplotlib
  - opencv==4.5.2
  - pip:
    - kornia_moons
    - kornia
