default: &default
    class: 'ASpanFormer'
    ckpt: 'pretrained/aspanformer/outdoor.ckpt'
    train_res: [832, 832]
    test_res: [832, 832]
    coarse_scale: 0.125
    coarsest_level: [26, 26]
    border_rm: 2
    imsize: 832
    online_resize: False
    match_threshold: 0.2
    no_match_upscale: False
example:
    <<: *default
hpatch:
    <<: *default
    no_match_upscale: True
megadepth:
    <<: *default
    coarsest_level: [36, 36]
    test_res: [1152, 1152]
scannet:
    <<: *default
    coarsest_level: [15, 20]
    train_res: [480, 640]
    border_rm: 0
inloc:
    <<: *default
    match_threshold: 0.2
    npts: 4096
    imsize: 1024
    pairs: 'pairs-query-netvlad40-temporal.txt'
    rthres: 48
    skip_matches: 20
aachen:
    <<: *default
    match_threshold: 0.0 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    npts: 4096
    imsize: 1024
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.2 # Filtering during quantization
    covis_cluster: True
